### ISSUE TITLE
Error when creating Tree object

### ISSUE THREAD

**Issue by pg** [yoyzhou/pyTree#1]
Maybe I'm just a n00b and I'm doing something wrong, but I'm seeing an error when I try to make a basic one-node Tree:

```
>>> t = Tree('Root')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File ".../lib/python2.7/site-packages/pyTree/Tree.py", line 24, in __init__
    self.data = data
File ".../lib/python2.7/site-packages/pyTree/Tree.py", line 56, in __setattr__
    super().__setattr__(name, value)
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by yoyzhou** [comment]
Hi Pgebhard,

PyTree only tested under support python 3.*, from the error trace I see that you use python 2.7 right?
In addition, did you install it via pypi? I apologize that the version at PyPi is out of date, please fork the latest version.

Thanks,
Yoyo

**Comment by pg** [comment]
Yes, I think it's an incompatibility since I'm using Python 2.7...
